env:
  global:
    - BRANCH=stable
    - UML_FIG=0
    - UML_DOCKERCOMPOSE=1

sudo: true

install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - ./run 'docker-compose run web python manage.py test'