env:
  global:
    - BRANCH=stable
    - UML_FIG=0
    - UML_DOCKERCOMPOSE=1
  matrix:
    - BRANCH=v1.0.0
    - BRANCH=stable
    - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=aufs
    - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=devicemapper
    - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=vfs
    - BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=devicemapper
    - BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=vfs
    # broken matrix
    - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=btrfs
    - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=overlay
    - BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=aufs
    - BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=btrfs
    - BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=overlay

sudo: true

install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - ./run 'docker-compose run web python manage.py test'