db:
  image: postgres

uwsgi:
  restart: always
  image: neurovault/neurovault
  volumes:
    - .:/code
  links:
    - db
    - redis
  volumes:
    - /var/www/static
    - /var/www/images

nginx:
  restart: always
  image: nginx
  ports:
    - "80:80"
  volumes:
    - nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
  volumes_from:
    - uwsgi
  links:
    - uwsgi

redis:
  restart: always
  image: redis